postgres:
  name: postgres
  namespace: database
  instances: 3
  storageClass: standard
  storageSize: 50Gi
  resources:
    requests:
      cpu: "4"
      memory: 7Gi
  postgresql:
    parameters:
      max_connections: "500"

backup:
  destinationPath: s3://my-postgres-backups/database
  endpointURL: https://s3.amazonaws.com
  retentionPolicy: 30d
