apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Values.postgres.namespace }}
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: {{ .Values.postgres.name }}
  podMetricsEndpoints:
    - port: metrics
      interval: 30s