apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-barman-plugin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default

  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: plugin-barman-cloud
    targetRevision: 0.6.0
    helm:
      releaseName: plugin-barman-cloud

  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
