apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "86.1.0"
    helm:
      releaseName: kube-prometheus-stack
      valuesObject:
        prometheus:
          prometheusSpec:
            podMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
            probeSelectorNilUsesHelmValues: false
            podMonitorNamespaceSelector: {}
            podMonitorSelector: {}

        grafana:
          enabled: true
          adminPassword: "change-me"
          sidecar:
            dashboards:
              enabled: true
              label: grafana_dashboard
              labelValue: "1"

        alertmanager:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
