---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: appsecret
  namespace: default
spec:
  encryptedData:
    apikey: AgB9Qah9hxFp909iS/nJcvYEVCm0Ic0sUnWgYOWPGQial3DDF9pZeiYj3RRKscw+zcmmAdZERH+vamfKkdWOV7p0RoMIAe0UyIe40AyqqTxO0xIGenXGKE62S0RMe7AJ9FCgEZnzP4ViQfwHJsYGcj4qrXf6HFXnKOO+sUzEM5/ydaDWE3nByd9n2s6WM3iFKP55pC2LpmdPFAdLo+MGyrz7J/t0mY5CqBfce2lUAhUiIoca/bba18JaKDET/5AzFtOlWfyTjZrvm+sSwXJN3dCmZN7ifTI3iHP9ysPwzdkBte4D+8MclRdts3WjYqyOjDYopp7gFZCyTRtiEaB5P/pICAoWz4/1eAhSfY+NHZYO5aG91up50v0hKE3z4jgmVYw5Gj12j3VkMHcOQtpyVBS0nv3CmVX4Aj4NohcqOlFrT+F0CBgdQmmObAq24aNjJF6EQoH4Z8kCtGCx5f/pvhoc0gjRxp7ZJjo4lD8ZofVEmLg7jUWxhkUv7qGc05BtPmvLWzwL1Cu7V83bpCopntTLHT8ZvHzoNSSxNvZ1TDnevydUF6WX9mMV2p4wlnl5w2cuTO5bWlpGuLVLE3G/IerG/K27Lsza+UYcmlHZh/vAMjAOyxFtUHXLYHIVQ1XO5xV/E7TzX3V/IQY+hZkVIEhdwxYqBhbF8gaNY9+PuelPxlBoxeMhTAm1V/upWN7/ram1qd99pLDOadkGsFpWQHVoj2p+PHc=
  template:
    metadata:
      name: appsecret
      namespace: default
    type: Opaque
